all:
  hosts:
    azure_vm:
      ansible_host: 0.0.0.0  # Replace with actual Azure Public IP after terraform apply
      ansible_user: adminuser
      ansible_password: password
      ansible_connection: ssh
      # Ignore SSH host key checking for ease of dev testing
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
